### ISSUE TITLE
OPC-UA server problem with certificate?

### ISSUE THREAD

**Issue by jbarbosa29** [ctron/de.dentrassi.camel.milo#10]
Hi Jens,

I've a problem connecting to a OPC-UA server. The error is depicted below. Can anyone, help me solving this issue? 

`org.eclipse.milo.opcua.stack.core.UaSerializationException: javax.xml.stream.XMLStreamException: Trying to output second root, <ServerCertificate>
        at org.eclipse.milo.opcua.stack.core.serialization.xml.XmlEncoder.write(XmlEncoder.java:384)[73:org.eclipse.milo.stack-core:0.1.0]
        at org.eclipse.milo.opcua.stack.core.serialization.xml.XmlEncoder.writeValue(XmlEncoder.java:389)[73:org.eclipse.milo.stack-core:0.1.0]
        at org.eclipse.milo.opcua.stack.core.serialization.xml.XmlEncoder.encodeByteString(XmlEncoder.java:207)[73:org.eclipse.milo.stack-core:0.1.0]
        at org.eclipse.milo.opcua.stack.core.types.structured.EndpointDescription.encode(EndpointDescription.java:111)[73:org.eclipse.milo.stack-core:0.1.0]
        at org.apache.camel.component.milo.client.internal.SubscriptionManager.toString(SubscriptionManager.java:514)[54:de.dentrassi.camel.milo.camel-milo:0.1.0]
        at org.apache.camel.component.milo.client.internal.SubscriptionManager.performConnect(SubscriptionManager.java:458)[54:de.dentrassi.camel.milo.camel-milo:0.1.0]
        at org.apache.camel.component.milo.client.internal.SubscriptionManager.connect(SubscriptionManager.java:380)[54:de.dentrassi.camel.milo.camel-milo:0.1.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
Caused by: javax.xml.stream.XMLStreamException: Trying to output second root, <ServerCertificate>
        at com.ctc.wstx.sw.BaseStreamWriter.throwOutputError(BaseStreamWriter.java:1537)[78:woodstox-core-asl:4.4.1]
        at com.ctc.wstx.sw.BaseStreamWriter.throwOutputError(BaseStreamWriter.java:1544)[78:woodstox-core-asl:4.4.1]
        at com.ctc.wstx.sw.BaseStreamWriter.reportNwfStructure(BaseStreamWriter.java:1572)[78:woodstox-core-asl:4.4.1]
        at com.ctc.wstx.sw.BaseNsStreamWriter.checkStartElement(BaseNsStreamWriter.java:469)[78:woodstox-core-asl:4.4.1]
        at com.ctc.wstx.sw.BaseNsStreamWriter.writeStartElement(BaseNsStreamWriter.java:290)[78:woodstox-core-asl:4.4.1]
        at org.eclipse.milo.opcua.stack.core.serialization.xml.XmlEncoder.write(XmlEncoder.java:375)[73:org.eclipse.milo.stack-core:0.1.0]
        ... 13 more`

Thank you.

**Comment by gbrost** [comment]
Sorry, i did not work with authenticated connections so far. And that is where this problem occurs, it seems.

**Comment by ctron** [comment]
This looks strange to me. But from the stack trace it looks to me as if this is a problem in the OPC UA layer in [Eclipse Milo](https://github.com/eclipse/milo). So I would kindly ask you to raise an issue with them.

**Comment by ctron** [comment]
I published a new version to Maven Central a few minutes ago (version 0.1.1). This should fix this issue.

It would be great if you could give it a try and give some feedback. Thanks!

**Comment by jbarbosa29** [comment]
Thank you so much. The problem is now solved. 
Nevertheless, the
 `feature:repo-add mvn:de.dentrassi.camel.milo/feature/0.1.1-SNAPSHOT/xml/features` should be `feature:repo-add mvn:de.dentrassi.camel.milo/feature/0.1.1/xml/features`

**Comment by ctron** [comment]
It should be 0.1.2 in the most recent README ... or did you spot another location?!

**Comment by ctron** [comment]
I was wrong. It should be 0.1.1 instead of 0.1.2 ... fixed this!

**Comment by jbarbosa29** [comment]
No, now it's fine. Good work.

**Comment by ctron** [comment]
Thanks a lot for reporting and testing!
